CREATE TABLE IF NOT EXISTS a_inputs_outputs_c (
    a INTEGER  NOT NULL,
    input_1 INTEGER NOT NULL,
    input_2 INTEGER NOT NULL,
    output_1 INTEGER NOT NULL,
    output_2 INTEGER NOT NULL,
    c INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS probability_a_c (
    a INTEGER NOT NULL,
    c INTEGER NOT NULL,
    probability REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS key_1_1 (
    key INTEGER NOT NULL
);